In [1]:
import cv2 as cv
import numpy as np

In [5]:
planets = cv.imread('../../imgs/Chapter03/3.11/planet_glow.jpg')
gray = cv.cvtColor(planets, cv.COLOR_BGR2GRAY)

img = cv.medianBlur(gray, 5)

circles = cv.HoughCircles(img, cv.HOUGH_GRADIENT, 1, 120, param1=90, param2=50, minRadius=0, maxRadius=0)
circles = np.uint16(np.around(circles))

In [6]:
for i in circles[0, :]:
    cv.circle(planets, (i[0], i[1]), i[2], (0, 255, 0), 2)
    cv.circle(planets, (i[0], i[1]), 2, (0, 0, 255), 3)
    print(i)
    
cv.imwrite('../../imgs/Chapter03/3.11/Circle.png', planets)

[480  80  72]
[516 234  71]
[332 224  61]
[326 370  73]
[128 228  64]
[300  84  74]
[142  82  67]


True