# 图像处理

傅里叶变换：看到的波形都是由其他波形叠加得到的，从而区分变化特别强的区域信号，标记噪声、感兴趣、前景和背景区域

### 高通滤波器

In [1]:
import cv2 as cv
import numpy as np
from scipy import ndimage

In [2]:
kernel_3x3 = np.array([[-1, -1, -1], 
                       [-1,  8, -1], 
                       [-1, -1, -1]])
kernel_5x5 = np.array([[-1, -1, -1, -1, -1],
                       [-1,  1,  2,  1, -1],
                       [-1,  2,  4,  2, -1],
                       [-1,  1,  2,  1, -1],
                       [-1, -1, -1, -1, -1]])

In [3]:
img_ori = cv.imread('../../imgs/Chapter03/3.2/Snipaste.png', cv.IMREAD_GRAYSCALE)

k3 = ndimage.convolve(img_ori, kernel_3x3)
k5 = ndimage.convolve(img_ori, kernel_5x5)

blurred = cv.GaussianBlur(img_ori, (11, 11), 0)
cv.imwrite("../../imgs/Chapter03/3.2/blurred.png", blurred)
g_hpf = img_ori - blurred

In [14]:
src = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

dst = ndimage.convolve(src, kernel_3x3)
print(dst)

[[-12  -9  -6]
 [ -3   0   3]
 [  6   9  12]]


In [7]:
cv.imwrite("../../imgs/Chapter03/3.2/k3.png", k3)
cv.imwrite("../../imgs/Chapter03/3.2/k5.png", k5)
cv.imwrite("../../imgs/Chapter03/3.2/g_hpf.png", g_hpf)

True

In [4]:
img_ori_color = cv.imread('../../imgs/Chapter03/3.2/Snipaste.png')
kernel_3x3x3 = np.array([[[-1, -1, -1], [-1, 8, -1], [-1, -1, -1]],
                       [[-1, -1, -1], [-1, 8, -1], [-1, -1, -1]],
                       [[-1, -1, -1], [-1, 8, -1], [-1, -1, -1]]])
k3_color = ndimage.convolve(img_ori_color, kernel_3x3x3)

cv.imwrite("../../imgs/Chapter03/3.2/k3_color.png", k3_color)

True

In [6]:
blurred_color = cv.GaussianBlur(img_ori_color, (11, 11), 0)
g_hpf_color = img_ori_color - blurred_color
cv.imwrite("../../imgs/Chapter03/3.2/g_hpf_color.png", g_hpf_color)

True